#!/bin/sh
#
# Validate the commit message. A commit will be aborted if
# - the commit message is empty
# - the last part of the branch name starts with "HPC-" but the commit message
#	  does not start with that last part of the branch name
#
# Convention for commit messages:
#	JIRA_TICKET_NUMBER: Message
#
# Example for a branch like "new-features/GHI-1234":
# GHI-1234: change description

# Check for empty commit message.
COMMIT_MSG=`cat $1`
if [[ -z $COMMIT_MSG ]]; then
	echo "Aborting commit due to empty commit message." >&2
	exit 1
fi

# Get the branch name. Only get the part after the last slash.
BRANCH_PATH=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_PATH##*/}

# Only act on branch names that are prefixed with HPC-
if [[ "$BRANCH_NAME" == "HPC-"* ]]; then
	if grep -qE "^Merge" "$1"; then
		# Do nothing if commit message starts with "Merge".
		exit 0
	fi

	# Now check if the commit message starts with the branch name. Abort if it
	# doesn't.
	ERROR_MSG="Aborting commit. Your commit message should start with the JIRA ticket number that matches your branch name ($BRANCH_NAME).
You can skip this check with the --no-verify option."
	if ! grep -iqE "^$BRANCH_NAME" "$1"; then
	    echo "$ERROR_MSG" >&2
	    exit 1
	fi
fi
