display:
  default:
    display_title: Master
    display_options:
      title: Media
      fields:
        media_bulk_form:
          action_title: Action
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: 'Apply filters'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
      filters:
        status:
          group_info:
            label: 'تم النشر'
            group_items:
              1:
                title: 'تم النشر'
              2:
                title: Unpublished
        name:
          expose:
            label: Name
        langcode:
          expose:
            label: Language
  page:
    display_title: Page
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
        name:
          separator: ', '
        edit_media:
          text: Edit
        delete_media:
          text: Delete
  widget:
    display_title: Widget
    display_options:
      arguments:
        bundle:
          exception:
            title: All
      filters:
        name:
          expose:
            label: Name
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Changed
      arguments:
        bundle:
          exception:
            title: All
      filters:
        name:
          expose:
            label: Name
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
