<?php

/**
 * @file
 * NCMS UI module file.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\ncms_ui\Controller\ViewController;
use Drupal\ncms_ui\Entity\Article;
use Drupal\ncms_ui\Entity\ContentSpaceAwareInterface;
use Drupal\ncms_ui\Entity\Document;
use Drupal\node\NodeInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ncms_ui_entity_bundle_info_alter(array &$bundles) {
  $bundles['node']['article']['class'] = Article::class;
  $bundles['node']['article']['label'] = t('Article');
  $bundles['node']['document']['class'] = Document::class;
  $bundles['node']['document']['label'] = t('Document');
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function ncms_ui_entity_base_field_info_alter(&$fields, $entity_type) {
  if ($entity_type->id() == 'node') {
    if (isset($fields['title'])) {
      $fields['title']->setDisplayConfigurable('view', TRUE);
    }
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function ncms_ui_local_tasks_alter(&$local_tasks) {
  // Remove the "View" tab from node edit pages.
  unset($local_tasks['entity.node.canonical']);
  // Rename the default menu tab on the content overview page to "Articles".
  $local_tasks['system.admin_content']['title'] = t('Articles');
}

/**
 * Implements hook_page_attachments_alter().
 */
function ncms_ui_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\Core\Extension\ExtensionPathResolver $extension_resolver */
  $extension_resolver = \Drupal::service('extension.path.resolver');
  $modules_path = $extension_resolver->getPath('module', 'ncms_ui');

  // Remove the default favicon.
  foreach ($attachments['#attached']['html_head_link'] as $key => $link) {
    if (!array_key_exists(0, $link) || !array_key_exists('rel', $link[0])) {
      continue;
    }
    if ($link[0]['rel'] == 'icon') {
      unset($attachments['#attached']['html_head_link'][$key]);
    }
  }

  // Set the new favicons.
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'apple-touch-icon',
    'href' => '/' . $modules_path . '/assets/favicons/apple-touch-icon.png',
    'sizes' => '180x180',
    'type' => 'image/png',
  ];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'icon',
    'href' => '/' . $modules_path . '/assets/favicons/favicon-32x32.png',
    'type' => 'image/png',
  ];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'icon',
    'href' => '/' . $modules_path . '/assets/favicons/favicon-16x16.png',
    'type' => 'image/png',
  ];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'manifest',
    'href' => '/' . $modules_path . '/assets/favicons/site.webmanifest',
  ];

  $is_gin = \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'gin';
  if ($is_gin) {
    $attachments['#attached']['library'][] = 'ncms_ui/ncms_gin';
  }
}

/**
 * Implements template_preprocess_html().
 */
function ncms_ui_preprocess_html(&$variables) {
  // Hide admin toolbar.
  $route_name = \Drupal::routeMatch()->getRouteName();
  $routes = [
    'entity.node.standalone',
    'entity.node.preview',
  ];
  if (in_array($route_name, $routes)) {
    if (!empty($variables['page_top']['toolbar'])) {
      unset($variables['page_top']['toolbar']);
    }
    if (!empty($variables['attributes']['class'])) {
      $variables['attributes']['class'] = array_filter($variables['attributes']['class'], function ($value) {
        return strpos($value, 'toolbar-') !== 0;
      });
    }
    $variables['attributes']['class'][] = 'ncms-node-preview';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function ncms_ui_preprocess_page(&$variables) {
  // Not technically necessary, but by attaching these 2 libraries, we will get
  // the same outline look of the modal dialogs (specifically when it comes to
  // the outer borders) for the node preview (coming from the node edit form)
  // and the node view in modal (coming from the admin content listing).
  $variables['#attached']['library'][] = 'core/jquery.ui.autocomplete';
  $variables['#attached']['library'][] = 'core/drupal.dialog';
}

/**
 * Implements hook_preprocess_page().
 */
function ncms_ui_preprocess_node(&$variables) {
  if (in_array($variables['elements']['#view_mode'], ['teaser', 'teaser_card'])) {
    $variables['page'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_layout_paragraphs_builder().
 */
function ncms_ui_preprocess_layout_paragraphs_builder(&$variables) {
  $variables['#attached']['library'][] = 'ncms_ui/layout_paragraphs';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_ui_form_node_preview_form_select_alter(&$form, FormStateInterface $form_state) {
  // Disable the view mode selection on the node previews. All we want to see
  // is the full page preview.
  $form['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_ui_form_layout_paragraphs_component_form_alter(&$form, FormStateInterface $form_state) {
  // Don't trigger "Required" messages when canceling the add/eddit form.
  $form['actions']['cancel']['#limit_validation_errors'] = [];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_ui_form_node_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  foreach (array_keys($form['actions']) as $action) {
    // Add our own submit handlers to redirect to the front page after saving a
    // node, which is set to be /admin/content.
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'ncms_ui_node_form_submit';
    }
  }
  // Change the behavior of the preview button to show the node preview in a
  // modal using an iframe.
  $form['actions']['preview']['#ajax'] = [
    'callback' => [ViewController::class, 'previewModal'],
    'event' => 'click',
  ];

  if ($node instanceof Document) {
    // Attach custom styles.
    $form['#attached']['library'][] = 'ncms_ui/document_edit_form';
  }

  if ($node instanceof Article) {
    // Hide the label of the double field widget.
    $form['field_caption']['widget'][0]['#title_display'] = FALSE;
    // Attach custom styles.
    $form['#attached']['library'][] = 'ncms_ui/article_edit_form';
  }

  /** @var \Drupal\ncms_ui\ContentManager $content_manager */
  $content_manager = \Drupal::service('ncms_ui.content.manager');

  // Check if this is a new content space aware node and if the content spaces
  // should be restricted for the current user.
  if ($node->isNew() && $node instanceof ContentSpaceAwareInterface && $content_manager->shouldRestrictContentSpaces()) {
    $content_space_ids = $content_manager->getValidContentSpaceIdsForCurrentUser();
    if (empty($content_space_ids)) {
      // This user needs a content space first and is currently not allowed to
      // create new content.
      \Drupal::messenger()->addWarning(t('You are currently not allowed to create content. Please contact our support.'));
      $form['#disabled'] = TRUE;
    }
    else {
      $content_space_widget = &$form['field_content_space']['widget'];
      $content_space_widget['#options'] = array_intersect_key($content_space_widget['#options'], $content_space_ids + ['_none' => TRUE]);
      if (count($content_space_ids) == 1) {
        $content_space_widget['#default_value'] = $content_space_ids;
        $content_space_widget['#disabled'] = TRUE;
      }
    }
  }

  // Add a cancel link. This either redirects to the publisher site if this
  // request came from an external publisher, or to a url given in the
  // destination query argument, or, as a fallback, to the main content
  // overview page.
  /** @var \Drupal\ncms_publisher\PublisherManager $publisher_manager */
  $publisher_manager = \Drupal::service('ncms_publisher.publisher.manager');
  $publisher_redirect = $publisher_manager->getCurrentRedirectUrl();

  $redirect_label = $publisher_redirect ? (string) t('Back to @publisher', [
    '@publisher' => $publisher_manager->getCurrentPublisher()->label(),
  ]) : NULL;

  // Take the destination only if it's not pointing to the current edit page.
  $current_destination = \Drupal::destination()->get();
  $destination_redirect = $node->id() && $current_destination != $node->toUrl('edit-form')->toString() ? $current_destination : NULL;

  // Set the redirect url. Publishers have priority, otherwise take the
  // destination if it's available.
  $redirect_url = $publisher_redirect ? Url::fromUri($publisher_redirect) : NULL;
  if (!$redirect_url && $destination_redirect) {
    $redirect_url = url::fromUserInput($destination_redirect);
  }
  // And if we still don't have a valid redirect, use the fallback.
  if (!$redirect_url) {
    $redirect_url = Url::fromRoute('system.admin_content');
  }

  $is_gin = \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'gin';
  if ($is_gin) {
    $form['#attached']['library'][] = 'ncms_ui/ncms_gin';
    $form['#attached']['drupalSettings']['ncms_gin']['redirect_url'] = $redirect_url->toString();
    if ($redirect_label) {
      $form['#attached']['drupalSettings']['ncms_gin']['redirect_label'] = $redirect_label;
    }
  }
  else {
    $form['actions']['cancel'] = [
      '#type' => 'link',
      '#title' => t('Cancel'),
      '#url' => $redirect_url,
      '#weight' => 20,
    ];
  }
}

/**
 * Implements hook_form_alter().
 */
function ncms_ui_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, '_replicate_form')) {
    /** @var \Drupal\ncms_ui\Form\ReplicateFormAlter $replicate_form_alter */
    $replicate_form_alter = \Drupal::service('ncms_ui.replicate_form_alter');
    $replicate_form_alter->alterForm($form, $form_state);
  }
}

/**
 * Custom submit function for the node article edit form.
 *
 * Checks if the edit request came from a trusted publisher, if not the user
 * will be redirected to the front page.
 */
function ncms_ui_node_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\ncms_publisher\PublisherManager $publisher_manager */
  $publisher_manager = \Drupal::service('ncms_publisher.publisher.manager');
  if (!$publisher_manager->getCurrentPublisher()) {
    $form_state->setRedirectUrl(Url::fromUserInput('/'));
  }
}

/**
 * Implements hook_link_alter().
 */
function ncms_ui_link_alter(&$variables) {
  /** @var \Drupal\Core\Url $url */
  $url = $variables['url'];
  if ($url->isRouted() && $url->getRouteName() == 'entity.node.canonical') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($url->getRouteParameters()['node']);
    $variables['options']['attributes']['title'] = t('Show a preview of this @bundle', [
      '@bundle' => strtolower(\Drupal::entityTypeManager()->getStorage('node_type')->load($node->bundle())->label()),
    ]);
    $variables['options']['attributes']['class'][] = 'use-ajax';
    $variables['options']['attributes']['data-dialog-type'] = 'modal';
    $variables['options']['attributes']['data-dialog-options'] = Json::encode([
      'width' => '80%',
      'title' => t('Preview: @title', ['@title' => $variables['text']]),
      'dialogClass' => 'node-preview',
    ]);
    $variables['url'] = Url::fromRoute('entity.node.iframe', ['node' => $node->id()]);
    $variables['#attached']['library'] = ['ncms_ui/node_preview'];
  }
}

/**
 * Implements hook_views_data_alter().
 */
function ncms_ui_views_data_alter(&$data) {
  // New comments are only supported for node table because it requires the
  // history table.
  $data['node']['article_document'] = [
    'title' => t('Document'),
    'help' => t('Lists the documents in which a node appears.'),
    'field' => [
      'id' => 'article_document_field',
      'no group by' => TRUE,
      'click sortable' => FALSE,
    ],
  ];
}

/**
 * Implements hook_node_access_records().
 */
function ncms_ui_node_access_records(NodeInterface $node) {
  if (!$node->hasField('field_content_space')) {
    return [];
  }

  $grants = [];
  $grants[] = [
    'realm' => 'ncms_ui_node_access_by_content_space',
    'gid' => 0,
    'grant_view' => $node->isPublished(),
    'grant_update' => 0,
    'grant_delete' => 0,
    'priority' => 0,
  ];

  // Get the team id from the current node if it's available.
  $content_space_id = !$node->field_content_space->isEmpty() ? $node->field_content_space->entity->tid->value : NULL;
  if (!$content_space_id) {
    return $grants;
  }
  $grants[] = [
    'realm' => 'ncms_ui_node_access_by_content_space',
    'gid' => $content_space_id,
    'grant_view' => 1,
    'grant_update' => 1,
    'grant_delete' => 1,
    'priority' => 0,
  ];

  return $grants;
}

/**
 * Implements hook_node_grants().
 */
function ncms_ui_node_grants(AccountInterface $account, $op) {
  $grants = [];
  $grants['ncms_ui_node_access_by_content_space'] = [0];

  $user = User::load($account->id());
  if (!$user->hasField('field_content_spaces')) {
    return $grants;
  }

  $content_spaces = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties([
    'vid' => 'content_space',
  ]);
  if ($user->hasPermission('administer nodes') && !empty($content_spaces)) {
    $grants['ncms_ui_node_access_by_content_space'] = array_merge($grants['ncms_ui_node_access_by_content_space'], array_values(array_map(function ($term) {
      /** @var \Drupal\taxonomy\Entity\Term $term */
      return $term->id();
    }, $content_spaces)));
  }
  elseif (!$user->field_content_spaces->isEmpty()) {
    foreach ($user->field_content_spaces->referencedEntities() as $content_space) {
      $grants['ncms_ui_node_access_by_content_space'][] = $content_space->tid->value;
    }
  }
  return $grants;
}
