<?php

/**
 * @file
 * NCMS UI module file.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\ncms_ui\Controller\ViewController;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function ncms_ui_entity_base_field_info_alter(&$fields, $entity_type) {
  if ($entity_type->id() == 'node') {
    if (isset($fields['title'])) {
      $fields['title']->setDisplayConfigurable('view', TRUE);
    }
  }
}

/**
 * Implements template_preprocess_html().
 */
function ncms_ui_preprocess_html(&$variables) {
  // Hide admin toolbar.
  $route_name = \Drupal::routeMatch()->getRouteName();
  $routes = [
    'entity.node.standalone',
    'entity.node.preview',
  ];
  if (in_array($route_name, $routes)) {
    if (!empty($variables['page_top']['toolbar'])) {
      unset($variables['page_top']['toolbar']);
    }
    if (!empty($variables['attributes']['class'])) {
      $variables['attributes']['class'] = array_filter($variables['attributes']['class'], function ($value) {
        return strpos($value, 'toolbar-') !== 0;
      });
    }
  }
}

/**
 * Implements hook_local_tasks_alter().
 */
function ncms_ui_local_tasks_alter(&$local_tasks) {
  unset($local_tasks['entity.node.canonical']);
}

/**
 * Implements hook_page_attachments_alter().
 */
function ncms_ui_page_attachments_alter(array &$attachments) {
  /** @var \Drupal\Core\Extension\ExtensionPathResolver $extension_resolver */
  $extension_resolver = \Drupal::service('extension.path.resolver');
  $modules_path = $extension_resolver->getPath('module', 'ncms_ui');

  // Remove the default favicon.
  foreach ($attachments['#attached']['html_head_link'] as $key => $link) {
    if (!array_key_exists(0, $link) || !array_key_exists('rel', $link[0])) {
      continue;
    }
    if ($link[0]['rel'] == 'icon') {
      unset($attachments['#attached']['html_head_link'][$key]);
    }
  }

  // Set the new favicons.
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'apple-touch-icon',
    'href' => '/' . $modules_path . '/assets/favicons/apple-touch-icon.png',
    'sizes' => '180x180',
    'type' => 'image/png',
  ];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'icon',
    'href' => '/' . $modules_path . '/assets/favicons/favicon-32x32.png',
    'type' => 'image/png',
  ];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'icon',
    'href' => '/' . $modules_path . '/assets/favicons/favicon-16x16.png',
    'type' => 'image/png',
  ];
  $attachments['#attached']['html_head_link'][][] = [
    'rel' => 'manifest',
    'href' => '/' . $modules_path . '/assets/favicons/site.webmanifest',
  ];

  $is_gin = \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'gin';
  if ($is_gin) {
    $attachments['#attached']['library'][] = 'ncms_ui/ncms_gin';
  }
}

/**
 * Implements hook_preprocess_page().
 */
function ncms_ui_preprocess_page(&$variables) {
  // Not technically necessary, but by attaching these 2 libraries, we will get
  // the same outline look of the modal dialogs (specifically when it comes to
  // the outer borders) for the node preview (coming from the node edit form)
  // and the node view in modal (coming from the admin content listing).
  $variables['#attached']['library'][] = 'core/jquery.ui.autocomplete';
  $variables['#attached']['library'][] = 'core/drupal.dialog';
}

/**
 * Implements hook_preprocess_page().
 */
function ncms_ui_preprocess_node(&$variables) {
  if (in_array($variables['elements']['#view_mode'], ['teaser', 'teaser_card'])) {
    $variables['page'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_layout_paragraphs_builder().
 */
function ncms_ui_preprocess_layout_paragraphs_builder(&$variables) {
  $variables['#attached']['library'][] = 'ncms_ui/layout_paragraphs';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_ui_form_node_preview_form_select_alter(&$form, FormStateInterface $form_state) {
  // Disable the view mode selection on the node previews. All we want to see
  // is the full page preview.
  $form['#access'] = FALSE;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_ui_form_layout_paragraphs_component_form_alter(&$form, FormStateInterface $form_state) {
  // Don't trigger "Required" messages when canceling the add/eddit form.
  $form['actions']['cancel']['#limit_validation_errors'] = [];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_ui_form_node_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  foreach (array_keys($form['actions']) as $action) {
    // Add our own submit handlers to redirect to the front page after saving a
    // node, which is set to be /admin/content.
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'ncms_ui_node_form_submit';
    }
  }
  // Change the behavior of the preview button to show the node preview in a
  // modal using an iframe.
  $form['actions']['preview']['#ajax'] = [
    'callback' => [ViewController::class, 'previewModal'],
    'event' => 'click',
  ];

  if ($node->getType() == 'document') {
    $form['#attached']['library'][] = 'ncms_ui/document_edit_form';
  }

  // Add a cancel link. This either redirects to the publisher site if this
  // request came from an external publisher, or to a url given in the
  // destination query argument, or, as a fallback, to the main content
  // overview page.
  /** @var \Drupal\ncms_publisher\PublisherManager $publisher_manager */
  $publisher_manager = \Drupal::service('ncms_publisher.publisher.manager');
  $publisher_redirect = $publisher_manager->getCurrentRedirectUrl();

  $redirect_label = $publisher_redirect ? (string) t('Back to @publisher', [
    '@publisher' => $publisher_manager->getCurrentPublisher()->label(),
  ]) : NULL;

  // Take the destination only if it's not pointing to the current edit page.
  $current_destination = \Drupal::destination()->get();
  $destination_redirect = $node->id() && $current_destination != $node->toUrl('edit-form')->toString() ? $current_destination : NULL;

  // Set the redirect url. Publishers have priority, otherwise take the
  // destination if it's available.
  $redirect_url = $publisher_redirect ? Url::fromUri($publisher_redirect) : NULL;
  if (!$redirect_url && $destination_redirect) {
    $redirect_url = url::fromUserInput($destination_redirect);
  }
  // And if we still don't have a valid redirect, use the fallback.
  if (!$redirect_url) {
    $redirect_url = Url::fromRoute('view.content.page_all_content');
  }

  $is_gin = \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'gin';
  if ($is_gin) {
    $form['#attached']['library'][] = 'ncms_ui/ncms_gin';
    $form['#attached']['drupalSettings']['ncms_gin']['redirect_url'] = $redirect_url->toString();
    if ($redirect_label) {
      $form['#attached']['drupalSettings']['ncms_gin']['redirect_label'] = $redirect_label;
    }
  }
  else {
    $form['actions']['cancel'] = [
      '#type' => 'link',
      '#title' => t('Cancel'),
      '#url' => $redirect_url,
      '#weight' => 20,
    ];
  }
}

/**
 * Custom submit function for the node article edit form.
 *
 * Checks if the edit request came from a trusted publisher, if not the user
 * will be redirected to the front page.
 */
function ncms_ui_node_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\ncms_publisher\PublisherManager $publisher_manager */
  $publisher_manager = \Drupal::service('ncms_publisher.publisher.manager');
  if (!$publisher_manager->getCurrentPublisher()) {
    $form_state->setRedirectUrl(Url::fromUserInput('/'));
  }
}

/**
 * Implements hook_link_alter().
 */
function ncms_ui_link_alter(&$variables) {
  /** @var \Drupal\Core\Url $url */
  $url = $variables['url'];
  if ($url->isRouted() && $url->getRouteName() == 'entity.node.canonical') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = \Drupal::entityTypeManager()->getStorage('node')->load($url->getRouteParameters()['node']);
    $variables['options']['attributes']['title'] = t('Show a preview of this @bundle', [
      '@bundle' => strtolower(\Drupal::entityTypeManager()->getStorage('node_type')->load($node->bundle())->label()),
    ]);
    $variables['options']['attributes']['class'][] = 'use-ajax';
    $variables['options']['attributes']['data-dialog-type'] = 'modal';
    $variables['options']['attributes']['data-dialog-options'] = Json::encode([
      'width' => '80%',
      'title' => t('Preview: @title', ['@title' => $variables['text']]),
      'dialogClass' => 'node-preview',
    ]);
    $variables['url'] = Url::fromRoute('entity.node.iframe', ['node' => $node->id()]);
    $variables['#attached']['library'] = ['ncms_ui/node_preview'];
  }
}

/**
 * Implements hook_views_data_alter().
 */
function ncms_ui_views_data_alter(&$data) {
  // New comments are only supported for node table because it requires the
  // history table.
  $data['node']['article_document'] = [
    'title' => t('Document'),
    'help' => t('Lists the documents in which a node appears.'),
    'field' => [
      'id' => 'article_document_field',
      'no group by' => TRUE,
      'click sortable' => FALSE,
    ],
  ];
}
