<?php

/**
 * @file
 * GHO NCMS module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gho_ncms_form_node_article_edit_form_alter(&$form, FormStateInterface $form_state) {
  $form['status']['widget']['value']['#title'] = t('Publicly available over API');
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'gho_ncms_node_article_edit_form_submit';
    }
  }
}

/**
 * Custom submit function for the node article edit form.
 *
 * Checks if the edit request came from a trusted publisher and redirects back
 * to it if requested.
 */
function gho_ncms_node_article_edit_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\gho_ncms\PublisherManager $publisher_manager */
  $publisher_manager = \Drupal::service('gho_ncms.publisher.manager');
  $response = $publisher_manager->getCurrentRedirectResponse();
  if ($response) {
    $form_state->setResponse($response);
    // Cleanup messages.
    \Drupal::messenger()->deleteAll();
  }
}
