<?php

/**
 * @file
 * GHO NCMS module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\TrustedRedirectResponse;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function gho_ncms_form_node_article_edit_form_alter(&$form, $form_state) {
  $form['status']['widget']['value']['#title'] = t('Publicly available over API');
  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'gho_ncms_node_article_edit_form_submit';
    }
  }
}

/**
 * Custom submit function for the node article edit form.
 *
 * Checks if the edit request came from a trusted publisher and redirects back
 * to it if requested.
 */
function gho_ncms_node_article_edit_form_submit($form, FormStateInterface $form_state) {
  $query = \Drupal::request()->query;
  if ($query->has('publisher') && $query->has('publisher_destination')) {
    /** @var \Drupal\gho_ncms\PublisherManager $publisher_manager */
    $publisher_manager = \Drupal::service('gho_ncms.publisher.manager');
    $publisher = $publisher_manager->getPublisher($query->get('publisher'));
    $host = parse_url($query->get('publisher_destination'), PHP_URL_HOST);
    if ($publisher && $host && $publisher->isKnownHost($host)) {
      $response = new TrustedRedirectResponse($query->get('publisher_destination'));
      $form_state->setResponse($response);
    }
  }
}
