ncms_publisher.publisher.*:
  type: config_entity
  label: 'Publisher config'
  mapping:
    id:
      type: string
      label: 'ID'
      constraints:
        NotNull: []
    label:
      type: label
      label: 'Label'
    known_hosts:
      type: text
      label: 'Known hosts'
    refresh_notifications_enabled:
      type: boolean
      label: 'Send refresh notifications'
    refresh_endpoint:
      type: uri
      label: 'Refresh endpoint'
    refresh_secret:
      type: string
      label: 'Refresh secret'
    uuid:
      type: string
      constraints:
        Uuid: []
