<?php

/**
 * @file
 * GHO General module file.
 */

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_element_info_alter().
 *
 * Add pre and post render callbacks to ensure the contextual links and
 * admin toolbar are always rendered with the site default language.
 */
function gho_general_element_info_alter(array &$info) {
  $ids = ['contextual_links', 'toolbar'];
  foreach ($ids as $id) {
    if (isset($info[$id])) {
      gho_general_add_language_switch_callbacks($info[$id]);
    }
  }
}

/**
 * Add pre and post render callbacks to switch the language to a render element.
 *
 * @param array $element
 *   A renderable array.
 */
function gho_general_add_language_switch_callbacks(array &$element) {
  if (!isset($element['#pre_render'])) {
    $element['#pre_render'] = [];
  }
  array_unshift($element['#pre_render'], 'gho_general_switch_language_pre_render');
  $element['#post_render'][] = 'gho_general_switch_language_post_render';
}

/**
 * Switch to the site default language before rendering the given element.
 *
 * @param array $element
 *   A renderable array.
 *
 * @return array
 *   A renderable array.
 */
function gho_general_switch_language_pre_render(array $element) {
  $element['#original_langcode'] = gho_general_switch_to_language();
  return $element;
}

/**
 * Switch back to the current language after rendering the given element.
 *
 * @param string $content
 *   Rendered element's content.
 * @param array $element
 *   A renderable array.
 *
 * @return array
 *   A renderable array.
 */
function gho_general_switch_language_post_render($content, array $element) {
  if (isset($element['#original_langcode'])) {
    gho_general_switch_to_language($element['#original_langcode']);
    unset($element['#original_langcode']);
  }
  return $content;
}

/**
 * Switch to the given language.
 *
 * @param string $langcode
 *   Language code to switch to. Empty to switch to the site's default language.
 *
 * @return string
 *   Current language code before the switch.
 */
function gho_general_switch_to_language($langcode = '') {
  $language_manager = \Drupal::service('language_manager');
  $translation_manager = \Drupal::service('string_translation');

  // Store the current language code.
  $current_langcode = $language_manager->getConfigOverrideLanguage()->getId();

  // Get the language associated with the langcode.
  if (!empty($langcode)) {
    $language = $language_manager->getLanguage($langcode);
  }

  // Use the site's default language.
  if (empty($language)) {
    $language = $language_manager->getDefaultLanguage();
  }

  // Change to the site default language.
  $language_manager->setConfigOverrideLanguage($language);
  $translation_manager->setDefaultLangcode($language->getId());

  return $current_langcode;
}

/**
 * Implements hook_entity_form_display_alter().
 *
 * Use the "homepage" form display mode for the home page.
 */
function gho_general_entity_form_display_alter(EntityFormDisplayInterface &$form_display, array $context) {
  if ($context['entity_type'] === 'node' && $context['bundle'] === 'article') {
    $nid = \Drupal::service('current_route_match')->getRawParameter('node');
    // The homepage is node 1.
    if ($nid == 1) {
      $storage = \Drupal::service('entity_type.manager')->getStorage('entity_form_display');
      $form_display = $storage->load('node.article.home_page');
    }
  }
}

/**
 * Implements hook_form_node_form_alter().
 */
function gho_general_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Ensure editors can publish/unpublish content.
  $form['status']['#access'] = TRUE;

  // Alter the promote option for the homepage to indicate it controls the
  // global visibility of the content for a given language.
  gho_general_alter_homepage_promote_checkbox($form, $form_state);

  // Set the form language direction.
  gho_general_set_form_language_direction($form, $form_state);
}

/**
 * Implements hook_form_media_form_alter().
 */
function gho_general_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set the form language direction.
  gho_general_set_form_language_direction($form, $form_state);
}

/**
 * Implements hook_form_taxonomy_term_form_alter().
 */
function gho_general_form_taxonomy_term_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Set the form language direction.
  gho_general_set_form_language_direction($form, $form_state);
}

/**
 * Set the language direction on the form.
 *
 * @param array $form
 *   Form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state.
 */
function gho_general_set_form_language_direction(array &$form, FormStateInterface $form_state) {
  $langcode = $form_state->get('langcode');
  if (isset($langcode)) {
    $language = gho_general_form_language_static($langcode);
    $form['#attributes']['lang'] = $language->getId();
    $form['#attributes']['dir'] = $language->getDirection();
  }
}

/**
 * Store the language direction so we can update ckeditor.
 *
 * @param string|null $langcode
 *   Code of the language for which to get the direction.
 *
 * @return string
 *   Language direction.
 */
function gho_general_form_language_static($langcode = NULL) {
  static $language = NULL;
  if (!isset($language)) {
    $language_manager = \Drupal::service('language_manager');
    if (isset($langcode)) {
      $language = $language_manager->getLanguage($langcode);
    }
    if (empty($language)) {
      $language = $language_manager->getDefaultLanguage();
    }
  }
  return $language;
}

/**
 * Implements hook_editor_js_settings_alter().
 *
 * Set the language for the content of the editors but keep UI in English.
 */
function gho_general_editor_js_settings_alter(&$settings) {
  $language = gho_general_form_language_static();
  if (isset($language)) {
    foreach ($settings['editor']['formats'] as &$editor) {
      $editor['editorSettings']['contentsLanguage'] = $language->getId();
      $editor['editorSettings']['contentsLangDirection'] = $language->getDirection();
    }
  }
}

/**
 * Switch to the site default language before rendering the given element.
 *
 * @param array $element
 *   A renderable array.
 *
 * @return array
 *   A renderable array.
 */
function gho_general_form_switch_language_pre_render(array $element) {
  if (isset($element['#langcode'])) {
    $element['#original_langcode'] = gho_general_switch_to_language($element['#langcode'], FALSE);
  }
  return $element;
}

/**
 * Switch back to the current language after rendering the given element.
 *
 * @param string $content
 *   Rendered element's content.
 * @param array $element
 *   A renderable array.
 *
 * @return array
 *   A renderable array.
 */
function gho_general_form_switch_language_post_render($content, array $element) {
  if (isset($element['#original_langcode'])) {
    gho_general_switch_to_language($element['#original_langcode'], FALSE);
    unset($element['#original_langcode']);
  }
  return $content;
}

/**
 * Alter the promote checkbox on the homepage.
 *
 * Make it more visible in the form and show it controls language visibility.
 *
 * @param array $form
 *   Form element.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   Form state.
 */
function gho_general_alter_homepage_promote_checkbox(array &$form, FormStateInterface $form_state) {
  $storage = $form_state->getStorage();
  if (isset($storage['form_display'], $storage['langcode']) && $storage['form_display']->getMode() === 'home_page') {
    $promote_title = t("Enable global visibility of @language content", [
      '@language' => \Drupal::service('language_manager')
        ->getLanguage($storage['langcode'])
        ->getName(),
    ]);
    $form['promote']['#access'] = TRUE;
    $form['promote']['#group'] = 'footer';
    $form['promote']['widget']['#title'] = $promote_title;
    $form['promote']['widget']['value']['#title'] = $promote_title;
  }
}

/**
 * Implements hook_form_menu_link_content_menu_link_content_form_alter().
 *
 * Use a textarea for the menu link title so that we can put line breaks to
 * control where the label breaks when displayed by adding line breaks.
 */
function gho_general_form_menu_link_content_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (isset($form['title']['widget']['0']['value']['#type'])) {
    $form['title']['widget']['0']['value']['#type'] = 'textarea';
  }
}

/**
 * Implements hook_preprocess_media().
 */
function gho_general_preprocess_media(&$variables) {
  gho_general_flag_untranslated('media', $variables);
}

/**
 * Implements hook_preprocess_node().
 */
function gho_general_preprocess_node(&$variables) {
  gho_general_flag_untranslated('node', $variables);
}

/**
 * Implements hook_preprocess_taxonomy_term().
 */
function gho_general_preprocess_taxonomy_term(&$variables) {
  gho_general_flag_untranslated('term', $variables);
}

/**
 * Flag the entity as not having a translation for the current language.
 *
 * @param string $entity_key
 *   Key to retrieve the entity from the variables array.
 * @param array $variables
 *   Variables array as passed to a hook_preprocess().
 */
function gho_general_flag_untranslated($entity_key, array &$variables) {
  static $is_administrator;

  if (!isset($is_administrator)) {
    $is_administrator = User::load(\Drupal::currentUser()->id())->hasRole('administrator');
  }

  if (isset($variables[$entity_key]) && $is_administrator) {
    $langcode = $variables[$entity_key]->language()->getId();

    if ($langcode !== \Drupal::service('language_manager')->getConfigOverrideLanguage()->getId()) {
      $variables['attributes']['class'][] = $entity_key . '--untranslated';
    }
  }
}
