<?php

/**
 * @file
 * NCMS module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\ncms_ui\Entity\ContentBase;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ncms_publisher_form_node_form_alter(&$form, FormStateInterface $form_state) {
  /** @var \Drupal\node\NodeForm $form_object */
  $form_object = $form_state->getFormObject();
  $entity = $form_object->getEntity();
  if (!$entity instanceof ContentBase) {
    return;
  }

  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'ncms_publisher_node_article_edit_form_submit';
    }
  }
}

/**
 * Custom submit function for the node article edit form.
 *
 * Checks if the edit request came from a trusted publisher and redirects back
 * to it if requested.
 */
function ncms_publisher_node_article_edit_form_submit($form, FormStateInterface $form_state) {
  /** @var \Drupal\ncms_publisher\PublisherManager $publisher_manager */
  $publisher_manager = \Drupal::service('ncms_publisher.publisher.manager');
  $response = $publisher_manager->getCurrentRedirectResponse();
  if ($response) {
    $form_state->setResponse($response);
    // Cleanup messages.
    \Drupal::messenger()->deleteAll();
  }
  else {
    // Redirect to the front page.
    $form_state->setRedirectUrl(Url::fromUserInput('/'));
  }
}
