display:
  default:
    display_title: Master
    display_options:
      title: Registro
      fields:
        sensor_status:
          label: Status
        sensor_message:
          label: 'Mensaje de estado'
        execution_time:
          label: 'Tiempo de ejecución'
        timestamp:
          label: 'Sello temporal'
      pager:
        options:
          tags:
            next: 'next ›'
            previous: '‹ previous'
            first: '« first'
            last: 'last »'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      arguments:
        sensor_name:
          exception:
            title: All
  detail_page_log:
    display_options:
      fields:
        timestamp:
          label: 'Sello temporal'
        sensor_status:
          label: Status
        sensor_message:
          label: 'Mensaje de estado'
        execution_time:
          label: 'Tiempo de ejecución'
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Registro
