type_settings:
  states:
    draft:
      label: Borrador
    published:
      label: Publicado
    trash:
      label: Archived
  transitions:
    delete:
      label: Archive
    publish:
      label: Publicar
    restore_draft:
      label: 'Restaurar a Borrador'
