version: "2.1"

services:
  cli:
    volumes:
      - ${PROJECT_ROOT}/html/sites/simpletest/:/var/www/html/sites/simpletest:rw
    environment:
      - HID_CLIENT_ID
      - HID_CLIENT_SECRET
      - GRAPHQL_KEY
      - COMPOSER_MEMORY_LIMIT=-1

  browser:
    hostname: browser
    image: seleniarm/standalone-chromium:latest
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /tmp:/dev/shm
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    ports:
      - 5900:5900