services:
  cli:
    volumes:
      - ${PROJECT_ROOT}/html/sites/simpletest/:/var/www/html/sites/simpletest:rw
    environment:
      - HID_CLIENT_ID
      - HID_CLIENT_SECRET
      - GRAPHQL_KEY
      - COMPOSER_MEMORY_LIMIT=-1
      - XDEBUG_ENABLED=1
      - XDEBUG_MODE=off

  browser:
    hostname: browser
    image: selenium/standalone-chromium:latest
    volumes:
      # Workaround to avoid the browser crashing inside a docker container
      # See https://github.com/SeleniumHQ/docker-selenium#quick-start
      - /tmp:/dev/shm
      - ${PROJECT_ROOT}/logs/chromedriver:/var/log/chromedriver
    environment:
      - 'JAVA_OPTS=-Dwebdriver.chrome.logfile=/var/log/chromedriver/chromedriver.log -Dverbose -Dwhitelisted-ips='
      - 'SE_NODE_MAX_SESSIONS=2'
      - 'SE_NODE_STEREOTYPE={"browserName": "chrome"}'
    ports:
      - 5901:5900
      - 7901:7900
      - 4445:4444