display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        sensor_status:
          label: Status
        sensor_message:
          label: "Message d'état"
        timestamp:
          label: Horodatage
      title: Journal
      arguments:
        sensor_name:
          exception:
            title: All
  detail_page_log:
    display_options:
      fields:
        timestamp:
          label: Horodatage
        sensor_status:
          label: Status
        sensor_message:
          label: "Message d'état"
  page_1:
    display_title: Page
    display_options:
      menu:
        title: Journal
