disallowed_types:
  layout_twocol_interactive:
    first:
      negate: true
      paragraph_types:
        interactive_content: interactive_content
    second:
      negate: true
      paragraph_types:
        interactive_content: interactive_content
  layout_threecol_interactive:
    first:
      negate: true
      paragraph_types:
        interactive_content: interactive_content
    second:
      negate: true
      paragraph_types:
        interactive_content: interactive_content
    third:
      negate: true
      paragraph_types:
        interactive_content: interactive_content
