_core:
  default_config_hash: PeDvVH4C3IZ7QFkvC1BUv3BZJVc7jLwQmJAEttVuVOw
frequency: 432000
offset: 604800
user_expire_roles:
  authenticated: 0
  administrator: 0
  google_login: 15552000
  un_agency_login: 0
send_expiration_warnings: true
expiration_warning_mail:
  subject: '[site:name]: Account expiration warning'
  body: "Hello [user:display-name]\r\n\r\nBecause you have not logged in recently, your account at [site:name] will be blocked in the near future. If you still use this site, log in now [site:login-url] to prevent your account being blocked.\r\n\r\n-- [site:name] team"
