<?php

/**
 * @file
 * GHO Footnotes module file.
 */

/**
 * Implements hook_theme().
 */
function gho_footnotes_theme() {
  return [
    'gho_footnote_list' => [
      'variables' => [
        'id' => '',
        'footnotes' => [],
      ],
    ],
    'gho_footnote' => [
      'variables' => [
        'id' => '',
        'content' => '',
        'backlinks' => [],
      ],
    ],
    'gho_footnote_backlink' => [
      'variables' => [
        'target' => '',
        'index' => '',
      ],
    ],
    'gho_footnote_reference' => [
      'variables' => [
        'id' => '',
        'target' => '',
        'index' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph__text().
 */
function gho_footnotes_preprocess_paragraph__text(&$variables) {
  // This module requires a field_footnotes to work with. If there is none
  // then skip the process entirely.
  if (!isset($variables['content']['field_footnotes'])) {
    return;
  }

  $renderer = \Drupal::service('renderer');

  // If there is no paragraph is (because it's new), then we generate a
  // temporary unique id. This mostly for when the paragraph is rendered in the
  // forms.
  $paragraph_id = $variables['paragraph']->id();
  if (empty($paragraph_id)) {
    $paragraph_id = \Drupal::service('uuid')->generate();
  }

  // We render the text to ensure all the text filters are applied (like
  // the one ensuring the HTML is correct) instead of using the raw text
  // because we will replace the references and add the footnotes that may not
  // have a markup compatible with some of the text filters (like removing some
  // classes).
  $field_text_text = '';
  if (isset($variables['content']['field_text'][0])) {
    $field_text_text = $renderer->renderPlain($variables['content']['field_text'][0]);
  }

  // We render the footnotes to ensure all the text filters are applied (like
  // the one ensuring the HTML is correct) instead of using the raw text
  // because we will generate the correct footnotes content and append it
  // to the text.
  $field_footnotes_text = '';
  if (isset($variables['content']['field_footnotes'][0])) {
    $field_footnotes_text = $renderer->renderPlain($variables['content']['field_footnotes'][0]);
  }

  // Extract the footnote references from the text.
  $references = gho_footnotes_extract_references($field_text_text);

  // Generate the footnotes. This will be an empty array if there are no
  // references to the footnotes or the footnotes don't match the references.
  $footnotes = gho_footnotes_generate_footnotes($paragraph_id, $field_footnotes_text, $references);

  // Hide the field as the footnotes are appended to the text directly.
  $variables['content']['field_footnotes']['#access'] = FALSE;

  // Update the references and add the footnotes to the text. We already
  // rendered the text, so we replace the field item with a simple markup type
  // render array.
  $variables['content']['field_text'][0] = [
    '#markup' => gho_footnotes_update_text($paragraph_id, $field_text_text, $references, $footnotes),
  ];
}

/**
 * Extract the references to footnotes from a text.
 *
 * @param string $text
 *   Text with footnote references.
 *
 * @return array
 *   Associative array with the footnote reference (ex: [1]) as keys and
 *   arrays of raw value + position of the references in the text, as values.
 */
function gho_footnotes_extract_references($text) {
  $references = [];
  if (preg_match_all('/ ?\[\d+\] ?/', $text, $matches, PREG_OFFSET_CAPTURE) !== FALSE) {
    foreach ($matches[0] as $match) {
      // Store the raw value and the position of the reference so we can easily
      // replace them.
      $references[trim($match[0])][] = [$match[0], $match[1]];
    }
  }
  return $references;
}

/**
 * Generate footnotes from a raw footnotes text.
 *
 * @param string $base_id
 *   Base id (ex: paragraph id).
 * @param string $text
 *   Footnotes HTML content where each paragraph (<p>) is a footnote.
 * @param array $references
 *   List of references to the footnotes.
 *
 * @return array
 *   List of footnotes keyed by their reference index (ex: [1]) and with an
 *   associative array containing the footnote id, its content and backlinks for
 *   each footnote.
 */
function gho_footnotes_generate_footnotes($base_id, $text, array $references) {
  $footnotes = [];
  // Once rendered the footnotes are separated by line breaks, so we can easily
  // split them.
  foreach (preg_split("/\n+/", $text) as $index => $content) {
    $reference = '[' . ($index + 1) . ']';
    $content = trim($content);
    if (!empty($content) && !empty($references[$reference])) {
      $footnote_id = 'footnote-' . $base_id . '-' . ($index + 1);
      $footnotes[$reference] = [
        '#theme' => 'gho_footnote',
        '#id' => $footnote_id,
        // The content of the footnote is already rendered HTML. This ensures
        // the markup is preserved and not encoded.
        '#content' => ['#markup' => $content],
        '#backlinks' => gho_footnotes_get_backlinks($footnote_id, $references[$reference]),
      ];
    }
  }
  return $footnotes;
}

/**
 * Get the reference backlinks for the footnote.
 *
 * @param string $footnote_id
 *   Footnote id.
 * @param array $references
 *   List of references to the footnote.
 *
 * @return array
 *   List of backlinks which are arrays with a target (id of the reference in
 *   the text) and a label.
 */
function gho_footnotes_get_backlinks($footnote_id, array $references) {
  $backlinks = [];
  foreach ($references as $index => $reference) {
    $backlinks[] = [
      '#theme' => 'gho_footnote_backlink',
      '#target' => $footnote_id . '-reference-' . ($index + 1),
      '#index' => $index + 1,
    ];
  }
  return $backlinks;
}

/**
 * Update the footnote references of a text.
 *
 * @param string $base_id
 *   Base id (ex: paragraph id).
 * @param string $text
 *   HTML text to update.
 * @param array $references
 *   List of references to footnotes.
 * @param array $footnotes
 *   List of footnotes keyed by reference.
 */
function gho_footnotes_update_text($base_id, $text, array $references, array $footnotes) {
  $renderer = \Drupal::service('renderer');
  // Start updating the references from the end to be able to use the extracted
  // positions otherwise they would not be correct after updating the first one.
  foreach (array_reverse($references) as $reference => $info) {
    $reference_index = substr($reference, 1, -1);

    // Get the footnote id for the reference. If not present, we will remove the
    // reference.
    $footnote_id = isset($footnotes[$reference]) ? $footnotes[$reference]['#id'] : NULL;

    // Start from the further reference in the text but preserve the index
    // as it's needed to generate the reference id for the backlinks.
    foreach (array_reverse($info, TRUE) as $index => list($value, $position)) {
      // Remove the reference and ensure we don't have double spaces left.
      if ($footnote_id === NULL) {
        $replacement = str_replace([$reference, '  '], ['', ' '], $value);
      }
      // Or generate the reference link.
      else {
        $element = [
          '#theme' => 'gho_footnote_reference',
          '#id' => $footnote_id . '-reference-' . ($index + 1),
          '#target' => $footnote_id,
          '#index' => $reference_index,
        ];
        // The str_replace here ensures the spaces surrounding the reference are
        // preserved. We cannot blindly trim the spaces because they may be of
        // significant value depending of the language. So this is left to the
        // editors to put appropriate spaces if necessary.
        $replacement = str_replace($reference, trim($renderer->render($element)), $value);
      }
      // Note that we don't use the mb_* functions to work with "bytes" so that
      // it's compatible with the PREG_OFFSET_CAPTURE flag used to extract the
      // references which returns the positions in the string in "bytes".
      $text = substr($text, 0, $position) . $replacement . substr($text, $position + strlen($value));
    }
  }
  // Append the footnotes to the text content.
  if (!empty($footnotes)) {
    $element = [
      '#theme' => 'gho_footnote_list',
      '#id' => 'footnote-list-' . $base_id,
      '#footnotes' => $footnotes,
    ];
    $text .= trim($renderer->render($element));
  }
  return $text;
}
