#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
		cp -f $source $dest
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Check if the local docksal environment file exists.
check_requirements()
{
  local_docksal_env="${PROJECT_ROOT}/.docksal/docksal-local.env"
  if [[ ! -f "${local_docksal_env}" ]]; then
    echo "Missing local environment file ${local_docksal_env}"
    echo "You can use the following command to create the file based on a template."
    echo "Once created, you need to fill in the values for the required environment variables."
    echo ""
    echo "  fin exec cp ${PROJECT_ROOT}/.docksal/default.docksal-local.env ${PROJECT_ROOT}/.docksal/docksal-local.env"
    echo ""
    exit 1
  fi
}

# Copy repo settings.php file into project
copy_settings ()
{
	copy_settings_file "${PROJECT_ROOT}/.docksal/settings/settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH
	# We disable email sending here so site-install does not return an error
	php -d sendmail_path=/bin/true /usr/local/bin/drush site-install -y --site-name='Humanitarian Action'
}

composer_install ()
{
	cd $PROJECT_ROOT
	composer install
}
#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
check_requirements
composer_install
copy_settings
fix_permissions
time site_install

echo -e "Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."

#-------------------------- END: Execution --------------------------------
