#!/usr/bin/env bash

## Login into the site.
##
## Usage: fin login [-h] [-u UID|-n name]
##

usage="$(basename "$0") [-h] [-u UID|-n name]

where:
    -h          show this help text
    -u|---uid   the UID to use for login
    -n|---name  the name to use for login"

# Login as user 1 by default.
USER_ID=1

while [ "$1" != "" ]; do
  case $1 in
    -u | --uid )          shift
                          USER_ID=$(fin drush user:information --uid=$1 --format=string --fields=uid)
                          STATUS=$?
                          if [[ $STATUS -eq 1 ]]; then
                            echo "No user found with the id ${1}"
                            exit 1
                          fi
                          USER_ID=${USER_ID//[$'\t\r\n']}
                          ;;
    -n | --name )         shift
                          USER_ID=$(fin drush user:information $1 --format=string --fields=uid)
                          STATUS=$?
                          if [[ $STATUS -eq 1 ]]; then
                            echo "No user found for the name ${1}"
                            exit 1
                          fi
                          USER_ID=${USER_ID//[$'\t\r\n']}
                          ;;
    -h | --help )         echo "$usage"
                          exit
                          ;;
    * )                   echo "$usage"
                          exit 1
  esac
  shift
done

URL=$(fin drush uli --uid ${USER_ID})
if [[ $URL =~ ^"http" ]]; then
  fin utils/open-link -i $URL
else
  echo "Can't generate login url"
  echo ${URL}
fi