#!/usr/bin/env bash

## Login into the site.
##
## Usage: fin login [-h] [-u UID]
##

usage="$(basename "$0") [-h] [-u UID]

where:
    -h  show this help text
    -u|---uid  the UID to use for login"

# Login as user 1 by default.
USER_ID=1

while [ "$1" != "" ]; do
  case $1 in
    -u | --uid )          shift
                          USER_ID=$1
                          ;;
    -h | --help )         echo "$usage"
                          exit
                          ;;
    * )                   echo "$usage"
                          exit 1
  esac
  shift
done

URL=$(fin drush uli --uid ${USER_ID})
fin utils/open-link -i $URL