#!/usr/bin/env bash

## Run project's PHPUnit tests.
##
## Usage: fin phpunit [arguments]

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

path="/var/www"
phpunit_xml_path="$PROJECT_ROOT/phpunit.xml"

cd $PROJECT_ROOT
if [[ ! -f "$phpunit_xml_path" ]]; then
  echo "Could not find $phpunit_xml_path"
  exit 1
fi

phpunit_path="vendor/bin/phpunit"
if [[ ! -f "$phpunit_path" ]]; then
  echo "Could not find $phpunit_path"
  exit 1
fi


COVERAGE=false
args=""
while [ "$1" != "" ]; do
  case $1 in
    --open-coverage )  COVERAGE=true
                       ;;
    *)                 args="$args $1"
                       ;;
  esac
  shift
done

fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} $path/$DOCROOT/modules/custom --coverage-html $path/$DOCROOT/sites/simpletest/test-coverage"

if $COVERAGE; then
  fin utils/open-link "http://ghi-site.docksal.site/sites/simpletest/test-coverage/dashboard.html"
fi