#!/usr/bin/env bash

## Run project's PHPUnit tests.
##
## Usage: fin phpunit [arguments]

# Environment variables passed from fin:
#
#   $PROJECT_ROOT - (string) absolute path to NEAREST .docksal folder
#   $VIRTUAL_HOST - (string) ex. projectname.docksal
#   $DOCROOT - name of the docroot folder
#   $DOCKER_RUNNING - (string) "true" or "false"

path="/var/www"
phpunit_xml_path="$PROJECT_ROOT/phpunit.xml"

cd $PROJECT_ROOT
if [[ ! -f "$phpunit_xml_path" ]]; then
  echo "Could not find $phpunit_xml_path"
  exit 1
fi

phpunit_path="vendor/bin/phpunit"
paraunit_path="vendor/bin/paraunit"

if [[ ! -f "$phpunit_path" ]]; then
  echo "Could not find $phpunit_path"
  exit 1
fi

COVERAGE=false
CLEAR_LOGS=false
PARALLEL=true
args=""
while [ "$1" != "" ]; do
  case $1 in
    -c | --clear-logs)
      CLEAR_LOGS=true
      ;;
    --open-coverage)
      COVERAGE=true
      ;;
    -s | --force-sequential)
      PARALLEL=false
      ;;
    *)
      args="$args $1"
      ;;
  esac
  shift
done

if $PARALLEL; then
  if [[ ! -f "$paraunit_path" ]]; then
    echo "Could not find $paraunit_path"
    exit 1
  fi
fi

timestamp=`date +%s`
COVERAGE_FILE="$path/$DOCROOT/sites/simpletest/coverage/coverage-${timestamp}.cov"

fin exec "mkdir -p $path/$DOCROOT/sites/simpletest/coverage"

if [ "${#args}" -eq 0 ] || $CLEAR_LOGS; then
  # Clear coverage repository if the full test suite is run, meaning phpunit is
  # invoked without any argument.
  fin exec "rm -r $path/$DOCROOT/sites/simpletest/browser-output/Drupal_* 2> /dev/null"
  fin exec "rm -r $path/$DOCROOT/sites/simpletest/coverage/* 2> /dev/null"
  fin exec "rm -r $path/$DOCROOT/sites/simpletest/coverage-html/* 2> /dev/null"
fi

# Always create a dedicated coverage file for each test run. They get later
# merged together into an HTML report
if $PARALLEL; then
  fin exec "XDEBUG_MODE=coverage $path/${paraunit_path} coverage -c $path ${args} --php $COVERAGE_FILE"
else
  fin exec "XDEBUG_MODE=coverage $path/${phpunit_path} -c $path ${args} --coverage-php $COVERAGE_FILE"
fi

# Create the HTML report.
fin exec "phpcov merge --html $path/$DOCROOT/sites/simpletest/coverage-html $path/$DOCROOT/sites/simpletest/coverage"

if $COVERAGE; then
  fin utils/open-link "http://${VIRTUAL_HOST}/sites/simpletest/coverage-html/dashboard.html"
fi