action.configuration.entity_publish:
  type: action_configuration_default
  label: 'Publish an entity'
action.configuration.entity_unpublish:
  type: action_configuration_default
  label: 'Unpublish an entity'
action.configuration.entity_move_to_trash:
  type: action_configuration_default
  label: 'Move an entity to the trash'