<?php

/**
 * @file
 * GHO Formatters.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_theme().
 */
function gho_fields_theme() {
  return [
    'gho_dataset_link_formatter' => [
      'variables' => [
        'url' => NULL,
        'source' => NULL,
      ],
    ],
    'gho_further_reading_link_formatter' => [
      'variables' => [
        'url' => NULL,
        'title' => NULL,
        'source' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_view_mode_alter().
 *
 * Change the view mode of the photo galleries based on the number of images
 * they contain.
 */
function gho_fields_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  if ($entity->getEntityTypeId() === 'paragraph' && $entity->bundle() == 'photo_gallery') {
    if ($entity->field_photos->count() % 2 === 0) {
      $view_mode = 'two_columns';
    }
    else {
      $view_mode = 'single_column';
    }
  }
}
