<?php

/**
 * @file
 * GHO Formatters.
 */

/**
 * Implements hook_theme().
 */
function gho_fields_theme() {
  return [
    'gho_dataset_link_formatter' => [
      'variables' => [
        'url' => NULL,
        'source' => NULL,
      ],
    ],
    'gho_further_reading_link_formatter' => [
      'variables' => [
        'url' => NULL,
        'title' => NULL,
        'source' => NULL,
      ],
    ],
  ];
}
